name: Deploy
on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref=='refs/head/main' }}
    steps:
      - run: |
          echo 'Event name: ${{ github.event_name }}'
          echo 'REf: ${{github.ref}}'
          echo 'Run number: ${{github.run_number}}'
